# Generated by Django 2.1.3 on 2018-12-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_componentofmaschine_componentofproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentmaschine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_text_maschine', models.CharField(max_length=200)),
                ('abilityofmaschine', models.CharField(max_length=200)),
                ('quality', models.IntegerField(default=0)),
                ('plant', models.CharField(max_length=200)),
                ('oee_componentofmaschine', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('maschine_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Maschine')),
            ],
        ),
        migrations.CreateModel(
            name='Componentproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_text_product', models.CharField(max_length=200)),
                ('shapeofproduct', models.CharField(max_length=200)),
                ('production', models.CharField(max_length=200)),
                ('product_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='componentofmaschine',
            name='maschine',
        ),
        migrations.RemoveField(
            model_name='componentofproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Componentofmaschine',
        ),
        migrations.DeleteModel(
            name='Componentofproduct',
        ),
    ]
