# Generated by Django 2.1.3 on 2018-12-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181219_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentmaschine',
            old_name='maschine_text',
            new_name='maschine',
        ),
        migrations.RenameField(
            model_name='componentproduct',
            old_name='product_text',
            new_name='product',
        ),
    ]
