# Generated by Django 2.1.3 on 2018-12-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_componentmaschine_maschine_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentproduct',
            name='product_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
