# Generated by Django 2.1.3 on 2019-01-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190114_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentmaschine',
            name='ability_multiaspect',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='diameter_tool',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='feedspeed',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='length_tool',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='rotatedspeed',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='strock',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='type_tool',
        ),
        migrations.RemoveField(
            model_name='componentmaschine',
            name='weight',
        ),
    ]
